stages:
  - build
  - tagging
  - release

build-latest:
  stage: build
  image: docker:18.09
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  services:
    - docker:18.09-dind
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - echo "$CI_REGISTRY_TOKEN" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - export RELEASE_TAG=$($CI_PROJECT_DIR/tools/parchant tags CHANGELOG.md)
    - echo $RELEASE_TAG
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker tag "$CI_REGISTRY_IMAGE:latest" "$CI_REGISTRY_IMAGE:$RELEASE_TAG"
    - docker push "$CI_REGISTRY_IMAGE:$RELEASE_TAG"

tagging-release:
  image: debian:buster-slim
  stage: tagging
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apt-get update -qy && apt-get install openssh-client git -qqy
    - eval `ssh-agent -s`
    - mkdir -p /root/.ssh
    - chmod 700 /root/.ssh
    - echo "$DEPLOY_KEY_PRIVATE" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
    - ssh-add /root/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - export RELEASE_TAG=$($CI_PROJECT_DIR/tools/parchant tags CHANGELOG.md)
  script:
    - git config --global user.email "dervishgaradex@gmail.com"
    - git config --global user.name "David Vrtěl"
    - git config --global url."ssh://git@gitlab.com/".insteadOf "https://github.com/"
    - git remote set-url origin git@gitlab.com:dergyitheron/telescoop.git
    - git tag -d $(git tag -l)
    - git tag ${RELEASE_TAG}
    - git push origin ${RELEASE_TAG}

publishing-release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - ./tools/parchant desc CHANGELOG.md > release_notes.txt
    - echo "Releasing version $CI_COMMIT_TAG"
  release:
    name: "Release $CI_COMMIT_TAG"
    description: "./release_notes.txt"
    tag_name: $CI_COMMIT_TAG
    ref: $CI_COMMIT_TAG
